# Site
repository: thaonguyen217/thaonguyen217.github.io
favicon: images/favicon.png

# Content configuration version
version: 2

# Personal info
name: Thao Nguyen
title: Incoming PhD student @ UIUC
email: thaotn2@illinois.edu
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username:  thaonguyen217
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: kaiaya10
linkedin_username: papaya3781
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi there, I'm Thao. Starting in August, I will begin my PhD studies at the University of Illinois at Urbana-Champaign under the guidance of Prof. Heng Ji.

  I received my BSc degree in Electrical Engineering from Hanoi University of Science and Technology (HUST) in late 2020. After graduation, I joined VinBigdata's AI Engineer training program and interned there for a year, working on medical image analysis research. I am currently a research assistant at the VinUni-Illinois Smart Health Center (VISHC), where I am focusing on deep learning algorithms to detect cardiovascular diseases utilizing ECG signals.

content:
  - title: Research interests # Title for the section
    layout: text
    content:
      Up until now, I have dabbled in a variety of machine learning domains, ranging from signal processing to computer vision to natural language processing. In the future, and as part of my PhD research, I will concentrate on <mark>meta-learning</mark> algorithms such as <mark>few-shot learning</mark>, <mark>curriculum learning</mark>, and <mark>active learning</mark>. My research goal is to develop algorithms that can improve convergence speed, be more adaptable to environmental changes, and generalize to a wider range of tasks.
#     layout: list # Type of content section (list/text)
#     content:
#       - layout: top-middle
#         title: Super awesome project
#         link: github.com/sproogen
#         # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
#           # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#           #   icon: fab fa-github
#           #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#         description: | # this will include new lines to allow paragraphs
#           I started this project as a way if learning <mark>
# React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: News # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Research assistant @ VISHC
        caption: Jan 2022 - present
        description: | # this will include new lines to allow paragraphs
            I started working at [VISHC](https://smarthealth.vinuni.edu.vn/) as a research assistant on the ECG signal analysis project.
      - layout: left
        title: Internship @ VinBidata
        caption: Jan 2021 - Dec 2022
        description: | # this will include new lines to allow paragraphs
            I started working at Medical Image Processing Department - [VinBigdata JSC](https://vinbigdata.com/en).
      - layout: left
        title: Undergrad
        caption: Dec 2020
        description: | # this will include new lines to allow paragraphs
            I received my BSc degree in Electrical Engineering from [HUST](https://hust.edu.vn/).

  - title: Publication # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      [6] Dat T. Ngo, <b>Thao Nguyen</b> , Hieu T. Nguyen, Dung B. Nguyen, Ha Q. Nguyen, Hieu H. Pham. [Slice-level Detection of Intracranial Hemorrhage on CT Using Deep Descriptors of Adjacent Slices](https://arxiv.org/abs/2208.03403). <i>2023 IEEE Statistical Signal Processing Workshop (SSP)</i>, 2023.  
      [5] <b>Thao Nguyen</b>, Hieu H. Pham, Khiem H. Le, Anh Tu Nguyen, Tien Thanh, Cuong Do. [Detecting COVID-19 from digitized ECG printouts using 1D convolutional neural networks](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0277081). <i>PLOS ONE</i>, 2022.  
      [4] <b>Thao Nguyen</b>, Tam M. Vo, Thang V. Nguyen, Hieu H. Pham, Ha Q. Nguyen. [Learning to diagnose common thorax diseases on chest radiographs from radiology reports in Vietnamese](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0276545). <i>PLOS ONE</i>, 2022.  
      [3] <b>Thao Nguyen</b>, Anh Tu Nguyen, Khiem H. Le, Hieu H. Pham, Cuong Do. [A novel deep learning-based approach for sleep apnea detection using single-lead ECG signals](https://www.researchgate.net/publication/362568235_A_novel_deep_learning-based_approach_for_sleep_apnea_detection_using_single-lead_ECG_signals). <i>APSIPA ASC - 2022</i>, 2022.  
      [2] Khiem H. Le, Hieu H. Pham, <b>Thao Nguyen</b>, Tu A. Nguyen, Tien N. Thanh, Cuong Do. [LightX3ECG: A Lightweight and eXplainable Deep Learning System for 3-lead Electrocardiogram Classification](https://www.researchgate.net/publication/362169587_LightX3ECG_A_Lightweight_and_eXplainable_Deep_Learning_System_for_3-lead_Electrocardiogram_Classification). <i>Biomedical Signal Processing and Control</i>, 2022.  
      [1] Khiem H. Le, Hieu H. Pham, <b>Thao Nguyen</b>, Tu A. Nguyen, Cuong Do. [Enhancing deep learning based 3-lead ECG classification with heartbeat counting and demographic data integration](https://www.researchgate.net/publication/362706895_Enhancing_Deep_Learning-based_3-lead_ECG_Classification_with_Heartbeat_Counting_and_Demographic_Data_Integration). <i>IECBES 2022</i>, 2022.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in research work some of my other interests and hobbies are:
      - Playing table tennis
      - Traveling
      - Photography
      - Drawing
      - Graphic design

#       Look at this cool image  
#      ![Drawing](/thaonguyen217.github.io/images/drawing.jpeg "Drawing")

# Footer
footer_show_references: true
references_title: Powered by Jekyll & AcademicPages, a fork of Minimal Mistakes.

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
